   name: OWASP ZAP SCAN OF A VULNERABLE WEB SITE
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.7.0
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target: 'http://testphp.vulnweb.com/'
